# Use the official AWS Lambda Node.js 18 image
FROM public.ecr.aws/lambda/nodejs:18

# Copy function code
COPY app.js package.json  ${LAMBDA_TASK_ROOT}/

# Install dependencies
RUN npm install

# Set the CMD to your handler
CMD ["app.handler"]
